# Generated by Django 3.1.1 on 2022-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('location', models.CharField(max_length=55)),
                ('publication_date', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
